### PR TITLE
fix: name and icon on app

### LINKED ISSUE #5: Displayed name on app icon
When the app is running the icon showed does not print Japanese characters correctly.

### PR DESCRIPTION
**Pull request by nukiro**
When the game is running the name and the icon was not showing good, so this `desktop` configuration fix it.

Closes #5

### CODE REVIEW

File: bushido/src/window.c [hunk 1]
```diff
@@ -2,9 +2,10 @@
 
 void window_init(const Game *g, Manager *m)
 {
-    InitWindow(m->window.width, m->window.height, g->name);
+    InitWindow(m->window.width, m->window.height, g->title);
+    SetWindowTitle(m->window.title);
     SetTargetFPS(GAME_FPS);
-    DBG("window open: %dx%d", m->window.width, m->window.height);
+    DBG("window %s open: %dx%d", g->title, m->window.width, m->window.height);
```
Comment (nukiro) [inline bushido/src/window.c:8]: Add both title from game and manager.

**Review by nukiro — COMMENTED** [review]
Added some comments and one fix.
